### ISSUE TITLE
Studio Feature Request: focus search when opening Open a Table page in Drizzle Studio

### ISSUE THREAD

**Issue by suraj5969** [drizzle-team/drizzle-kit-mirror#245]
when I click on + button in drizzle studio to open a new table, can we focus search for quick searching of tables,
and also, It would be great if we could have keyboard navigation, up and down arrow for selecting table and enter to open a table

**Comment by L-Mario564** [comment]
Studio UI has changes since this issue was created, so a the things mentioned either don't apply to the current UI or are already implemented. If there's a missing feature in the current version of Studio, feel free to open a new feature request over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
