### ISSUE TITLE
0.22.0 introduced breaking changes and should have been a major release...

### ISSUE THREAD

**Issue by fierysolid** [drizzle-team/drizzle-kit-mirror#455]
If you're going to deprecate fields in the config you should let people know with a major version bump.

**Comment by paolostyle** [comment]
https://semver.org/#spec-item-4

**Comment by fierysolid** [comment]
Is the drizzle-kit cli truly still in initial development or are you guys using the spec 4/major version 0 as a way to be lazy? The kit seem mature to me.

**Comment by paolostyle** [comment]
I'm not a maintainer, just pointing out that bumping a minor version when major is still 0 might contain breaking changes. 

My opinion on this is irrelevant, but as a regular user I do not think `drizzle-kit` is mature at all and far from stable.

**Comment by fierysolid** [comment]
Maybe we have different understanding of what "in development" means. This package has 250k weekly downloads and the first commit was two years ago. No package is ever truly stabile or mature that's why versions exist. This has way too many people using it to say it's still in development, that should be reserved for unreleased products.

**Comment by AndriiSherman** [comment]
We have a plan for what needs to be done before reaching version 1.0. The API is still changing, and the internal implementation is still evolving to reach a shape we consider ready for 1.0. We introduce significant changes with each release, such as versions 0.20.0, 0.21.0, and 0.22.0, and we anticipate further changes in 0.23.0.

We don't want to release versions 1.x, 2.x, and 3.x every few weeks. Instead, we aim to iterate quickly and deliver important features to users rapidly. That's why we follow semantic versioning (semver) rules, using 0.x releases.

Once we have a comprehensive set of tests, minimal open bugs for all kit commands, and necessary features such as rollback migrations, proper hints for your schema, and an improved push command, we will release version 1.0

**Comment by fierysolid** [comment]
You are correct though, I shouldn't have trusted a version zero package. My argument is that it shouldn't be version zero if hundreds of thousands of people use it.

**Comment by dankochetov** [comment]
@fierysolid until we release 1.0, we have "shifted" the versions, so minor updates become major and patch updates become minor, which means breaking changes are shipped in minor version updates. That's the only difference.

**Comment by fierysolid** [comment]
Okay this is using its own version rules. I'll have to remember I guess.
