### ISSUE TITLE
Drizzle kit applies multiple migration files in the same transaction

### ISSUE THREAD

**Issue by ahmedmoazasif** [drizzle-team/drizzle-kit-mirror#522]
If you have two separate migrations that haven't been deployed yet, drizzle-kit runs both the migrations as part of the same transaction.  This results in unwanted behaviour where a developer might have applied migration 1 then generated migration 2 and applied it and on deployment, both the migrations are run together. 

**Previous state:**
`my_table` has a column `type` of enum `my_type` with default `value`

**Goal:**
Add `new_value` to the `my_type` enum and set it as default for column `type` on `my_table`

**Migration 1:**
```sql
ALTER TYPE "my_type" ADD VALUE 'new_value';
```

**Migration 2:**
```sql
ALTER TABLE my_table  ALTER COLUMN "type" SET DEFAULT 'new_value'
```

**Expected behaviour:** 
Each migration is committed separately. 

**Actual behaviour:**
```
PostgresError: unsafe use of new value "new_value" of enum type "my_type"
```

**Present hack applied to resolve the issue:**
Added following lines to start of migration 2. 
```
COMMIT; -- Commit already present transaction
BEGIN; -- Begin new transaction
```

**Comment by jwatte** [comment]
This is likely the cause of #525

**Comment by firatoezcan** [comment]
Seems like you have a solution. It's definitely in the best interest to run multiple migrations in a single transaction because otherwise you are in an in-between state for which you probably don't have any application code.

Seems cumbersome, but having to fiddle with the generated migrations is nothing out of the ordinary, even though one would think otherwise. It's just a matter of databases being hard

**Comment by cmonaghan1** [comment]
> It's definitely in the best interest to run multiple migrations in a single transaction because otherwise you are in an in-between state for which you probably don't have any application code

From what I've seen, most other database migration management tools make a conscious decision not to run multiple migrations in a single transaction. I think you should aim to maintain backwards compatibility with your migrations and only look to make destructive changes well after your application code has ceased supporting whatever destructive change you are making.

Running multiple migrations in a single transaction can cause issues in unexpected ways, for example if you automatically deploy changes (and thus migrations) to a staging environment but not to production, you may find your migrations work perfectly in staging as they aren't batched in a single transaction but find performance degradation in your database due to locking if your next production deployment runs multiple migrations in a single transaction.

Providing the option to not run multiple migrations in a single transaction like other tools would be helpful here.

**Comment by L-Mario564** [comment]
We'll continue tracking this issue here: https://github.com/drizzle-team/drizzle-orm/issues/3249.
